### ISSUE TITLE
チュートリアルポップアップのアイコン画像作成

### ISSUE THREAD

**Issue by xiii111** [LITO-apps/Treevel-client#1221]
ref: https://github.com/LITO-apps/Treevel-client/issues/1073#issuecomment-939216266

### 経緯
#1201 を行うにあたって、リリース時に必要なチュートリアルポップアップに対して、アイコン画像が用意されている必要がある。表示名と説明については、#1203  で行うことにする。

### 備考
- アイコン画像は、原画をそのまま利用するとしても、別フォルダに配置する
- 1:1 以外の原画を利用する場合には、1:1 にリサイズして配置する

### 完了条件
以下の画像を作成し、適切な場所に配置後、適用する
#### ギミック
- [x] Tornado → #1196 で作成(Torando@spin-000を使う)
- [x] Meteorite → 原画を変換
- [x] AimingMeteorite → 原画を変換
- [x] Thunder → #1199 で作成
- [x] GustWind → #1070 で作成
- [x] Erasable → 原画を変換（gif がより良い）

#### タイル
- [x] Goal → 原画を変換（ #1143 により不要になりうる）
- [x] Warp → 原画を変換（gif がより良い）
- [x] Holy → 原画を変換
- [x] SpiderWeb → 原画を変換
- [x] Ice → 原画を変換

#### ボトル
- [x] Dynamic → 原画を変換
- [x] Static → 原画を変換
- [x] Goal → 原画を変換（ #1143 により不要になりうる）
- [x] AttackableDummy → 原画を変換

#### ボトルアトリビュート（赤ボトルにくっつける）
- [x] Dark → 原画を変換（gif がより良い）
- [x] Reverse → 原画を変換
- [x] Ghost → 原画を変換
- [x] Life → 原画を変換

**Comment by takasusuke** [comment]
一旦、全部画像で考える。

**Comment by takesi0627** [comment]
@takesi0627 
ライフアトリビュートのアイコン作成を頼む

**Comment by takesi0627** [comment]
@takasusuke 
アイコンのサイズどうする？
決めちゃってください

**Comment by takasusuke** [comment]
@takesi0627 
大体の素材を200x200でお願いしてるから、200x200予定です。

**Comment by takesi0627** [comment]
@takasusuke 
LifeAttributeの画像作りました。ご確認ください
https://drive.google.com/open?id=10hTjiMyMCGY-BP5yeJnW8e0dWrpo963V&authuser=woody90825.ep01%40g2.nctu.edu.tw&usp=drive_fs

**Comment by takesi0627** [comment]
https://drive.google.com/drive/folders/10ZLiIz8NsK-ZnZl2csJZxeExYMhW7rJX
フォルダはこちら

**Comment by takasusuke** [comment]
Tornado
```
$ convert Tornado@spin-000-origin.png -gravity center -crop 178x178-4+0 Tornado-crop.png
$ convert -resize 200x200 Tornado-crop.png Tornado.png
```

**Comment by takasusuke** [comment]
memo
- Meteoriteの画像変更
- TutorialとOverviewPopupで同じアセットを参照
- 動画のloop
